/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/task-details`; params?: Router.UnknownInputParams; } | { pathname: `/../src/screens/TaskListScreen copy/index`; params?: Router.UnknownInputParams; } | { pathname: `/../src/screens/TaskListScreen copy/TaskListScreen`; params?: Router.UnknownInputParams; } | { pathname: `/../src/screens/LoginScreen/index`; params?: Router.UnknownInputParams; } | { pathname: `/../src/screens/LoginScreen/LoginScreen`; params?: Router.UnknownInputParams; } | { pathname: `/../src/hooks/AuthContext`; params?: Router.UnknownInputParams; } | { pathname: `/../src/hooks/useAuth`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/task-details`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/screens/TaskListScreen copy/index`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/screens/TaskListScreen copy/TaskListScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/screens/LoginScreen/index`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/screens/LoginScreen/LoginScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/hooks/AuthContext`; params?: Router.UnknownOutputParams; } | { pathname: `/../src/hooks/useAuth`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/task-details${`?${string}` | `#${string}` | ''}` | `/../src/screens/TaskListScreen copy/index${`?${string}` | `#${string}` | ''}` | `/../src/screens/TaskListScreen copy/TaskListScreen${`?${string}` | `#${string}` | ''}` | `/../src/screens/LoginScreen/index${`?${string}` | `#${string}` | ''}` | `/../src/screens/LoginScreen/LoginScreen${`?${string}` | `#${string}` | ''}` | `/../src/hooks/AuthContext${`?${string}` | `#${string}` | ''}` | `/../src/hooks/useAuth${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/task-details`; params?: Router.UnknownInputParams; } | { pathname: `/../src/screens/TaskListScreen copy/index`; params?: Router.UnknownInputParams; } | { pathname: `/../src/screens/TaskListScreen copy/TaskListScreen`; params?: Router.UnknownInputParams; } | { pathname: `/../src/screens/LoginScreen/index`; params?: Router.UnknownInputParams; } | { pathname: `/../src/screens/LoginScreen/LoginScreen`; params?: Router.UnknownInputParams; } | { pathname: `/../src/hooks/AuthContext`; params?: Router.UnknownInputParams; } | { pathname: `/../src/hooks/useAuth`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
